import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';
import { enableProdMode } from '@angular/core';
import { AppModule } from './app/app.module';
import { registerLicense } from '@syncfusion/ej2-base';


registerLicense('Mgo+DSMBaFt+QHFqVkNrXVNbdV5dVGpAd0N3RGlcdlR1fUUmHVdTRHRcQlhiQH5bckdhXHtacnI=;Mgo+DSMBPh8sVXJ1S0d+X1RPd11dXmJWd1p/THNYflR1fV9DaUwxOX1dQl9gSXtSf0VrXX1cdXBTRGY=;ORg4AjUWIQA/Gnt2VFhhQlJBfV5AQmBIYVp/TGpJfl96cVxMZVVBJAtUQF1hSn5Wd0xjUXtccnFRQWha;MjExNjIxMkAzMjMxMmUzMTJlMzMzNWRqRTh3K2p6Tmo1eW9iKzFjK3M0Z2xFRFdUdk1mZGdYUHZna0poZzVkaFE9;MjExNjIxM0AzMjMxMmUzMTJlMzMzNUZtMCt0cW0rSlNESzBXOW1kdTM1b016ZVF5SVhzTkwrandEUmgxUzFsUlE9;NRAiBiAaIQQuGjN/V0d+XU9Hc1RDX3xKf0x/TGpQb19xflBPallYVBYiSV9jS31Tc0RqWXdacnZQQ2ZdVw==;MjExNjIxNUAzMjMxMmUzMTJlMzMzNU9NcGc5aFd4Qm93SkJhcVZEZUc4bTIwR2c3aGFQemNqdHllOE1OZTMrNmM9;MjExNjIxNkAzMjMxMmUzMTJlMzMzNWxwMTk4dnZ1WkZPODdlWnRucFZuZ2FVZlUwVEZ3NllIV3dzVkFVbEVkZVk9;Mgo+DSMBMAY9C3t2VFhhQlJBfV5AQmBIYVp/TGpJfl96cVxMZVVBJAtUQF1hSn5Wd0xjUXtccnFTQmha;MjExNjIxOEAzMjMxMmUzMTJlMzMzNWhFeU9EbFZIY3RJNi8xbWc3bTRWckxIbWFlY1JIVkV1aU5IVDBVRzdqa0U9;MjExNjIxOUAzMjMxMmUzMTJlMzMzNWJIdGNKRW90SzVGWjhhQUJuaGRoNm1QS0w3L3crVVRKT1BqTkQrZzdaSmM9;MjExNjIyMEAzMjMxMmUzMTJlMzMzNU9NcGc5aFd4Qm93SkJhcVZEZUc4bTIwR2c3aGFQemNqdHllOE1OZTMrNmM9');

enableProdMode();
platformBrowserDynamic().bootstrapModule(AppModule)
  .catch(err => console.error(err));
